[package]
name = "xword_gen"
version = "0.1.0"
edition = "2021"

[dependencies]
util = { path = "../util" }
dlx = { git = "https://github.com/ClaytonKnittel/dlx-rs.git", rev = "86f33e69023f978cca621dcde87164641d7cd341" }
itertools = "0.14.0"
googletest = "0.13.0"
rand = "0.9.0"
