[package]
name = "xword_gen"
version = "0.1.0"
edition = "2021"

[dependencies]
util = { path = "../util" }
dlx = { git = "https://github.com/ClaytonKnittel/dlx-rs.git", rev = "1c71071e5643e6ce77fda9ad597e2f6cbe339840" }
itertools = "0.14.0"
googletest = "0.13.0"
rand = "0.9.0"
