[package]
name = "xword_dict"
version = "0.1.0"
edition = "2021"

[dependencies]
util = { path = "../util" }
bitcode = { version = "0.6.4", features = ["derive"] }
itertools = "0.14.0"
regex = "1.11.1"
once_cell = "1.20.3"
